# https://github.com/crazy-max/goreleaser-xx

env:
  - GO111MODULE=auto

builds:
  - mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - goarm: "7"
    tap:
      owner: jzelinskie
      name: homebrew-faq
    folder: Formula
    homepage: https://github.com/jzelinskie/faq
    description: Format Agnostic jQ
    license: "Apache 2.0"
    dependencies:
      - name: jq
    test: |
      system "#{bin}/faq", "--version"
