name: demo

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  demo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        demo:
          - web
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      -
        name: Build goreleaser-xx
        uses: docker/bake-action@v1
        with:
          targets: image-local
      -
        name: Build demo
        uses: docker/bake-action@v1
        with:
          files: ./demo/${{ matrix.demo }}/docker-bake.hcl
          # TODO: Build multi-platform image but needs https://github.com/moby/buildkit/pull/2521 to load local image
          targets: image-local
          set: |
            *.context=./demo/${{ matrix.demo }}
            *.args.GORELEASER_XX_IMAGE=goreleaser-xx:local
