name: demo

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

jobs:
  demo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        demo:
          - c-goxx
          - c-xx-alpine
          - c-xx-debian
          - cpp-nummer
          - cpp-goxx
          - cpp-xx-alpine
          - echo-webapp
          - gorm-goxx
          - jq-goxx
          - with-config
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build goreleaser-xx
        uses: docker/bake-action@v1
        with:
          targets: image
          push: true
          set: |
            *.tags=localhost:5000/goreleaser-xx:local
      -
        name: Build demo
        uses: docker/bake-action@v1
        with:
          files: ./demo/${{ matrix.demo }}/docker-bake.hcl
          targets: artifact-all
          set: |
            *.context=./demo/${{ matrix.demo }}
        env:
          GORELEASER_XX_BASE: localhost:5000/goreleaser-xx:local
      -
        name: List artifacts
        run: |
          tree -nh ./dist
